# Generated by Django 5.0.7 on 2024-11-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_smart', '0005_remove_contadordata_sensor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contadordata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contadordata',
            name='valor',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='luminosidadedata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='luminosidadedata',
            name='valor',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='temperaturadata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='temperaturadata',
            name='valor',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='umidadedata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='umidadedata',
            name='valor',
            field=models.FloatField(null=True),
        ),
    ]
